version: 2.1

executors:
  node-executor:
    docker:
      - image: node:20.18.0 # Using the official Node.js Docker image

jobs:
  test:
    executor: node-executor
    steps:
      # Checkout the code from the repository
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Run Jest tests
      - run:
          name: Run Jest Tests
          command: npm test

workflows:
  version: 2
  test-on-main:
    jobs:
      - test
